### ISSUE TITLE
Localhost

### ISSUE THREAD

**Issue by Drillibit** [cesarve77/mandarina-boilerplate#1]
I would like to suggest using http://localhost:5577 instead of http://192.168.99.100:5577.

**Comment by cesarve77** [comment]
Did you try that in your computer.

My knowledge of docker are very very limited, I couldn't  do that because docker assigned that ip to the default machine.

Tell how can we changed

**Comment by Drillibit** [comment]
I tried that. The thing is,  http://192.168.99.100:5577 that address may not be exactly the same as it is in your machine. So when I ran it for the first time locally I got an error because of that path(it's a bit different on my machine). So I just deleted docker container.Here is how docker container ls then remove it with the command docker rm ***** <---container id I deleted both mysql:5.7 and prismagraphql/prisma:1.21. So I think we can consider this as an issue.

**Comment by cesarve77** [comment]
I understand, but how do we change it to localhost?

**Comment by Drillibit** [comment]
I simply replaced http://192.168.99.100:5577 with http://localhost:5577 everywhere and that's it. Then deleted the containers and compose them again.

**Comment by cesarve77** [comment]
Fine.

That's does not work on my computer.\

Is good to know

**Comment by Drillibit** [comment]
You mean  http://localhost:5577 doesn't work?

**Comment by cesarve77** [comment]
No in my machine . But I'm not expert in docker

**Comment by Drillibit** [comment]
Could you run this command --> docker container ls , and show me the output?

**Comment by cesarve77** [comment]
CONTAINER ID        IMAGE                       COMMAND
  CREATED
            STATUS              PORTS                    NAMES

35fc3974875f        mysql:5.7                   "docker-entrypoint.s…"   2
days ago          Up 2 days           0.0.0.0:3306->3306/tcp
prisma_study_tour_mysql_1

f69a43c73506        prismagraphql/prisma:1.21   "/bin/sh -c /app/sta…"   2
days ago          Up 2 days           0.0.0.0:4466->4466/tcp
prisma_study_tour_1

**Comment by cesarve77** [comment]
The documentation is changed, It created a ENV var for handle the IP.
and there is a command yarn run docker-ip to get the IP (docker-machine ip default)

https://github.com/cesarve77/mandarina-boilerplate/commit/7c070035bf1034105234d8e9a05e749af29cb5cf
